apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minio
  name: minio
  namespace: smart-hire-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        ports:
        - containerPort: 9090
        command:
        - /bin/bash
        - -c
        args:
        - minio server /data --console-address :9090
---
