apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: smart-hire-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: salaheddine122/gateway-service:1.0.0
        ports:
        - containerPort: 9999
        envFrom:
        - configMapRef:
            name: gateway-configmap
