apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultx
  namespace: smart-hire-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: vault:1.13.3
          ports:
            - containerPort: 8200
---
apiVersion: v1
kind: Service
metadata:
  name: vaultx-service
  namespace: smart-hire-ops
spec:
  selector:
    app: vault
  ports:
    - protocol: TCP
      port: 8200
      targetPort: 8200
  type: ClusterIP


