apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: smart-hire-ops
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8500
      targetPort: 8500
    - name: udp-dns
      protocol: UDP
      port: 8600
      targetPort: 8600
    - name: tcp-8502
      protocol: TCP
      port: 8502
      targetPort: 8502
  selector:
    app: consul
