apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: smart-hire-ops
spec:
  selector:
    app: minio
  ports:
    - name: web-interface
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: s3-api
      protocol: TCP
      port: 9000  
      targetPort: 9000
