name: Test pipeline

on:
  pull_request:
    paths:
        - 'web-services/gateway-service/**' 
  push:
    paths:
        - 'web-services/gateway-service/**'

env:
  SERVICE_NAME: gateway-service
  IMAGE_NAME: salaheddine122/
  APP_CONTEXT: web-services/gateway-service/
  PROJECT_PATH: ./web-services/gateway-service
  STAGING_ENV: refs/heads/staging
  PROD_ENV: refs/heads/main


      
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Maven clean package & test
        run: cd ${{ env.APP_CONTEXT }} && mvn clean package

      - name: Set up QEMU
        if: github.ref == ${{ env.STAGING_ENV }} || github.ref == ${{ env.PROD_ENV }}
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        if: github.ref == ${{ env.STAGING_ENV }} || github.ref == ${{ env.PROD_ENV }}
        uses: docker/setup-buildx-action@v3


      - name: Docker Login
        if: github.ref == ${{ env.STAGING_ENV }} || github.ref == ${{ env.PROD_ENV }}
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        if: github.ref == ${{ env.STAGING_ENV }} || github.ref == ${{ env.PROD_ENV }}
        uses: docker/build-push-action@v5.1.0
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}${{ env.SERVICE_NAME }}:1.0.0
          

      